# Generated by Django 6.0.2 on 2026-04-08 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_orderhistory_options_alter_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to='core.ownerprofile', verbose_name='Владелец'),
        ),
    ]
