# Generated by Django 6.0.2 on 2026-04-08 20:31

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_shop_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region='RU', unique=True, verbose_name='Номер телефона'),
        ),
    ]
