# Generated by Django 6.0.2 on 2026-05-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customerprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='brand_name',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Название бренда'),
        ),
    ]
