# Generated by Django 6.0.2 on 2026-03-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание тарифа'),
        ),
    ]
