# Generated by Django 6.0.2 on 2026-03-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tariff_description'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='goods_in_stock_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['shop', 'price'], name='sorted_prices_idx'),
        ),
    ]
