# Generated by Django 6.0.2 on 2026-03-23 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_goods_in_stock_idx_product_sorted_prices_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения заказа')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество товара')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser', verbose_name='Покупатель')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общая цена')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('shipped', 'Отправлен'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='pending', max_length=20, verbose_name='Статус товара')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.telegramuser', verbose_name='Покупатель')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shop', verbose_name='Магазин')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Товар(сохранненый)')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество товаров в заказе')),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за штуку')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Заказ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Заказы с товарами',
            },
        ),
    ]
