/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/core/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create User Endpoint */
        post: operations["core_api_create_user_endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/shop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Shop Endpoint */
        post: operations["core_api_create_shop_endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/product": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Product Endpoint */
        post: operations["core_api_create_product_endpoint"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/my-shops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List My Shops Endpoint */
        get: operations["core_api_list_my_shops_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/shops/{shop_id}/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Product List Endpoint */
        get: operations["core_api_product_list_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/product/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Product Endpoint */
        delete: operations["core_api_delete_product_endpoint"];
        options?: never;
        head?: never;
        /** Edit Products Endpoint */
        patch: operations["core_api_edit_products_endpoint"];
        trace?: never;
    };
    "/api/core/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Products Endpoint */
        get: operations["core_api_list_products_endpoint"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** TelegramUserOut */
        TelegramUserOut: {
            /** ID телеграмм пользователя */
            user_id: number;
            /**
             * Роль
             * @default customer
             */
            role: string;
        };
        /**
         * Roles
         * @enum {string}
         */
        Roles: "customer" | "owner";
        /** TelegramUserIn */
        TelegramUserIn: {
            /** User Id */
            user_id: number;
            role: components["schemas"]["Roles"];
            /** Phone Number */
            phone_number: string;
            /** Inn */
            inn?: string | null;
            /** Brand Name */
            brand_name?: string | null;
        };
        /** ShopOut */
        ShopOut: {
            /** Owner Id */
            owner_id: number;
            /** Id */
            id?: string | null;
            /** Название магазина */
            shop_name: string;
            /** Ссылка (slug) */
            shop_link: string;
        };
        /** ShopIn */
        ShopIn: {
            /** Owner */
            owner: number;
            /** Shop Name */
            shop_name: string;
            /** Shop Link */
            shop_link?: string;
        };
        /** ProductOut */
        ProductOut: {
            /**
             * Price
             * @example 0.00
             */
            price: string;
            /**
             * Shop Id
             * Format: uuid
             */
            shop_id: string;
            /** ID */
            id?: number | null;
            /** Название товара */
            title: string;
            /** Описание товара */
            description: string;
            /**
             * Осталось товара
             * @default 1
             */
            stock: number;
            /**
             * Доступен ли товар
             * @default true
             */
            is_active: boolean;
        };
        /** ProductIn */
        ProductIn: {
            /**
             * Shop
             * Format: uuid
             */
            shop: string;
            /** User Id */
            user_id: number;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Price */
            price: number | string;
            /** Stock */
            stock: number;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
        };
        /** ProductPatch */
        ProductPatch: {
            /** User Id */
            user_id: number;
            /** Title */
            title: string | null;
            /** Description */
            description: string | null;
            /** Price */
            price: number | string | null;
            /** Stock */
            stock: number | null;
            /** Is Active */
            is_active: boolean | null;
        };
        /** Input */
        Input: {
            /**
             * Limit
             * @default 100
             */
            limit: number;
            /**
             * Offset
             * @default 0
             */
            offset: number;
        };
        /** PagedProductOut */
        PagedProductOut: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Count */
            count: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    core_api_create_user_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TelegramUserIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TelegramUserOut"];
                };
            };
        };
    };
    core_api_create_shop_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShopIn"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOut"];
                };
            };
        };
    };
    core_api_create_product_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Images */
                    images: string[];
                    data: components["schemas"]["ProductIn"];
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
        };
    };
    core_api_list_my_shops_endpoint: {
        parameters: {
            query: {
                user_id: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShopOut"][];
                };
            };
        };
    };
    core_api_product_list_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shop_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"][];
                };
            };
        };
    };
    core_api_delete_product_endpoint: {
        parameters: {
            query: {
                owner_id: number;
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    core_api_edit_products_endpoint: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductPatch"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
        };
    };
    core_api_list_products_endpoint: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedProductOut"];
                };
            };
        };
    };
}
