import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans", // Верни нормальное имя
  subsets: ["latin", "cyrillic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Верни нормальное имя
  subsets: ["latin"],
});

// ... metadata ... в

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className="h-full">
      {/* МЫ ПРИМЕНЯЕМ ПЕРЕМЕННЫЕ И САМ КЛАСС FONT-SANS К BODY */}
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}